### PR TITLE
Do TZ conversions using new root server field

### PR DESCRIPTION
**Pull request by jbraswell**

### CODE REVIEW

**Comment by jbraswell** [comment]
DO NOT MERGE UNTIL VIRTUAL-NA IS USING THE NEW TIME ZONE FIELDS!

**Comment by jbraswell** [comment]
Pending review, this is ready

**Review by radius314 — APPROVED** [review]
You will need to bump the version (in readme.txt and crouton.php) and add release notes to readme.txt  but otherwise tests good.

**Comment by radius314** [comment]
Also need to bump here: https://github.com/bmlt-enabled/crouton/blob/proper-timezone-support/readme.txt#L8

**Pull request merged**
