### PR TITLE
Share button

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
image

**Comment by radius314** [comment]
image

**Comment by radius314** [comment]
image

**Comment by alanb2718** [comment]
The new button works nicely!  A minor issue: `#share-button.btn-xs` was added to most of the themes, but not the last 3 (seattle-rain, self, and truth).  Was this an oversight?  It still seems to work for those themes though using some inherited information.

If you want to add the German translation for "share" it would be "teilen".

**Pull request merged**
