### PR TITLE
default dropdown selection feature #200

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
You can do things like `[bmlt_tabs default_filter_dropdown="formats=closed"]`

**Comment by pjaudiomv** [comment]
Awesome

**Comment by radius314** [comment]
Can I get a review @pjaudiomv when you get a chance?

**Comment by radius314** [comment]
Ok will fix it.

**Comment by radius314** [comment]
pushed

**Comment by radius314** [comment]
Spaces should be separated with a hyphen.  Example `[bmlt_tabs default_filter_dropdown="formats=Basic-Text"]`

**Pull request merged**
