### PR TITLE
format templates to make them easier to modify and extend

### PR DESCRIPTION
**Pull request by alanb2718**

### CODE REVIEW

**Comment by alanb2718** [comment]
This is a partial response to issue #256.  It has better formatting for the templates, but doesn't support multiple templates or the TinyMCE editor.

**Comment by dgershman** [comment]
Do the back ticks work on older browsers?

**Comment by alanb2718** [comment]
How old?  There is a [stackoverflow post](https://stackoverflow.com/questions/27678052/usage-of-the-backtick-character-in-javascript#27678299) that says they are supported by  Firefox 34, Chrome 41, and Edge 12 and above, but not by Internet Explorer.  If this would be an issue I can rewrite this to use one string per line and concatenate them.  Ugly code, but the template would be ok.

**Comment by dgershman** [comment]
We have tried hard to keep support for IE up until now. I have deliberately
avoided using newer HTML and JavaScript features.  We could look in the
future at transpiling, but for now I’d stick with what would be supported.

—Danny

**Comment by alanb2718** [comment]
OK, will update the PR accordingly.

**Comment by dgershman** [comment]
https://github.com/bmlt-enabled/crouton/issues/216
https://github.com/bmlt-enabled/crouton/issues/72
https://github.com/bmlt-enabled/crouton/issues/106

**Comment by dgershman** [comment]
I don’t see a way to polyfill this either
https://stackoverflow.com/a/50458959.

**Review by dgershman — APPROVED** [review]

**Pull request merged**
