### PR TITLE
adding new helper functions for venue types

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Review by alanb2718 — APPROVED** [review]
Generally looks good!  Here are a couple of optional suggestions (but they are optional).

For `isInPersonOnly`, why the test that the meeting is `not TC`?  The only place the TC format should occur is for `Virtual (temporarily closed)` meetings, and the `not VM` test already takes care of that.  This won't hurt anything though; just not sure what it's for.

The pre-existing `isVirtual` test is a bit weird -- it checks for meetings that are `HY` but not `TC`, and there should never be such.  Otherwise it's redundant with the new `isVirtualOrHybrid` test, except that it's less clear from the name what it does.  So my suggestion is to add another test `isVirtualOnly` (which is true only for `VM` meetings, not `HY`), and to deprecate `isVirtual` (but don't remove it, since it's used in the current default template).

This would leave a clean range of tests: `isInPersonOnly`, `isHybrid`, and `isVirtualOnly`, plus combinations for `isInpersonOrHybrid` and `isVirtualOrHybrid`.  Or maybe `isHybrid` should be named `isHybridOnly` instead.

**Comment by radius314** [comment]
> For `isInPersonOnly`, why the test that the meeting is `not TC`? The only place the TC format should occur is for `Virtual (temporarily closed)` meetings, and the `not VM` test already takes care of that. This won't hurt anything though; just not sure what it's for.

There are still a number of root servers not yet on 2.16.0 (there are quite a few), wouldn't keeping this logic prevent confusion in case they are not using the new radio buttons?  This makes it backward compatible.

> The pre-existing `isVirtual` test is a bit weird -- it checks for meetings that are `HY` but not `TC`, and there should never be such. Otherwise, it's redundant with the new `isVirtualOrHybrid` test, except that it's less clear from the name what it does. So my suggestion is to add another test `isVirtualOnly` (which is true only for `VM` meetings, not `HY`), and to deprecate `isVirtual` (but don't remove it, since it's used in the current default template).

Again, my thinking is backward compatibility safety, there seems to be no harm done here.  We can certainly add another check, and also update the default template (and mark deprecated, although I have to tell you, we have no way to track what versions everyone is on, so things are there forever).

> This would leave a clean range of tests: `isInPersonOnly`, `isHybrid`, and `isVirtualOnly`, plus combinations for `isInpersonOrHybrid` and `isVirtualOrHybrid`. Or maybe `isHybrid` should be named `isHybridOnly` instead.

I'm apprehensive to rename anything that is used now, we can make it simply a pointer back to the newly named method as you suggested.

**Comment by radius314** [comment]
Back to our conversation on the last call we had, all of this is super hacky.  The root server should make venue a first class citizen.

**Comment by radius314** [comment]
@alanb2718 I have updated the PR, let me know your thoughts.

**Comment by radius314** [comment]
I took your suggestion and removed the !TC checks.  I also added commentary noting that these work only with >= 2.16.0

**Comment by alanb2718** [comment]
I agree the code for these tests is super hacky!  But the names and meanings of the tests seem reasonable in any case, and could still be supported for some subsequent release of the root server in which the venue is a first-class citizen.

My only remaining suggestions are to change this comment (5 places):
`Works with versions of root server 2.16.0 or greater`
to
`Assumes consistent set of venue type formats (enforced for newly edited meetings in root server 2.16.0 or greater)`

The idea is that it still may not work even in the latest root server release, since that enforces consistency only when you try to edit a meeting - there may be inconsistent formats for existing meetings.  Also they _might_ be consistent even for older releases. (Thinking about the four inconsistent sets of venue type formats, actually I think they work as well as is feasible for them too -- at least I couldn't think of additional hacks to work around possible errors -- but we can set that aside.)

Also change this comment (2 places):
`@deprecated Since version 2.16.2, will be removed in a future version.`
to
`@deprecated Since crouton version 3.12.2, will be removed in a future version.`

**Comment by radius314** [comment]
@alanb2718 Added recommended changes to comments.

**Comment by radius314** [comment]
@alanb2718 bump on this.

**Comment by alanb2718** [comment]
Oh, sorry!  Since you had incorporated my remaining suggestion, I thought this was OK (and actually I was going to ping **you** about doing the merge).

But as long as we're still looking at this code, what do you think about changing the definition of `isVirtual` to check for any of `virtual_meeting_link`, `phone_meeting_number`, or `virtual_meeting_additional_info`?  Right now it just checks for `virtual_meeting_link` or `phone_meeting_number`.  But we are allowing a virtual meeting to have just `virtual_meeting_additional_info`.  (As of root server 2.16.0 the editor gives a warning, but it is still allowed.)  The result of not having this test is that meetings with only this field don't show the `MEETS VIRTUALLY` label  in the right hand column in crouton.

**Comment by radius314** [comment]
> virtual_meeting_additional_info

added.

**Review by alanb2718 — APPROVED** [review]
Perfect!  This seems ready to merge now.

**Pull request merged**
