### PR TITLE
add class to selects on header template

### PR DESCRIPTION
**Pull request by pjaudiomv**
ok figured it out

fix for #112

### CODE REVIEW

**Comment by pjaudiomv** [comment]
the specificity was too generic just specifying a select box, so had to add class and specify that class

**Comment by pjaudiomv** [comment]
now when the page fully renders the select box classes end up being `class="crouton-select select2-hidden-accessible"`

working example is here https://staging1.nerna.org/meetings-by-area/boston-area-meetings/

**Comment by radius314** [comment]
Was this a breaking change of some sort?

**Comment by radius314** [comment]
Fixing a breaking change that is...

**Comment by pjaudiomv** [comment]
Yes that's correct the breaking change it fixes is referenced here #112

**Comment by radius314** [comment]
Is this fixing the breaking change or implementing some new thing that will have to be communicated to others that are utilizing custom CSS?

**Comment by pjaudiomv** [comment]
Crouton was turning any select box on a page into a select2 component

**Comment by radius314** [comment]
Ok that makes sense.

**Comment by pjaudiomv** [comment]
To my knowledge This should not effect anyone using custom css in any previous versions of crouton

**Pull request merged**
