### PR TITLE
Small change to google maps link on the "Map" button to include a marker

### PR DESCRIPTION
**Pull request by paulnagle**

### CODE REVIEW

**Comment by paulnagle** [comment]
This daddr link doesnt work well on iphones when there are no directions available. Will do some more research on it

**Comment by paulnagle** [comment]
Well, according to https://developers.google.com/maps/documentation/urls/guide the correct way to put together a google maps URL for a point on a map is :
https://www.google.com/maps/search/?api=1&query=51.89422183%2C-8.4691152
Or with directions:
https://www.google.com/maps/dir/?api=1&destination=51.89422183%2C-8.4691152
This still doesn't help with the "sometimes there is no marker" issue though

I get a marker on my phone, and on firefox on the desktop.. just not in chrome. So maybe its a chrome bug 

Either way, we should probably update the url  to be the format that google considers correct.

**Comment by radius314** [comment]
I had a user hit this issue on an Android phone using the yap summary page.  I wonder if it's possible to use both querystrings to support both scenarios.

**Comment by radius314** [comment]
I also wonder if it makes a difference using `,` versus the urlencoded version of comma `%2C`?

**Comment by paulnagle** [comment]
I haven't found a good solution for this. I don't think the problem is with how the url is formatted, I think the issue is with the location on the map that the lat/lng points to. I think that if Google Maps doesn't have what they call a `place`  at that location, then no pin is displayed.

**Comment by radius314** [comment]
will likely close in favor of https://github.com/bmlt-enabled/crouton/commit/f611624ca0ddf18eed22809a6e699b321fad4fe8, need to do some testing

**Pull request closed without merging**
