### PR TITLE
bumping wordpress compatibility to 5.4

### PR DESCRIPTION
**Pull request by pjaudiomv**
I bumped all bmlt readmes in svn to 5.4 https://wordpress.org/plugins/search/bmlt/ this just updates repo

### CODE REVIEW

**Comment by radius314** [comment]
Have you confirmed compatibility ?

>

**Comment by pjaudiomv** [comment]
Yes on all of them, not all are php 7.4 compatible but they are all 7.2 with WP 5.4

**Comment by radius314** [comment]
ok thanks, will cut a version tonight

**Comment by pjaudiomv** [comment]
no need to cut version unless you made other changes, the compatibility change to readme does not require a version bump. ```For each plugin that is compatible, you don't need to release a new version — just change the stable version's readme value.``` I have updated the readme value  in svn. all the bmlt plugins show at 5.4 now https://wordpress.org/plugins/search/bmlt/

**Pull request merged**
