### PR TITLE
share button accent fix

### LINKED ISSUE #358: Share button not working on some meetings
Some of the share buttons are not working when you click on them

Go to https://na-italia.org/riunioni/ and click on the share button (condividi), some will work others won't

**Expected behavior**
For all share buttons to work

### PR DESCRIPTION
**Pull request by dgershman**
fixes #358

### CODE REVIEW

**Comment by spiritualtheory** [comment]
Any chance you can make the share button optional (on by default) while you’re in there?

**Comment by dgershman** [comment]
> Any chance you can make the share button optional (on by default) while you’re in there?

I'm not understanding the use case where you would not want to share meeting information with someone.

**Review by jbraswell — APPROVED** [review]

**Comment by spiritualtheory** [comment]
> > Any chance you can make the share button optional (on by default) while you’re in there?
> 
> I'm not understanding the use case where you would not want to share meeting information with someone.

It’s less about not wanting to share, more about making the placement flexible rather than it must appear at the end of the metadata

**Comment by dgershman** [comment]
Ok the issue is that this feature is not part of the templating engine.  At this time I'm not sure I know what to do here, so I'm not going to address it now.

**Comment by pjaudiomv** [comment]
You could hide it with css for now

**Pull request merged**
